$ANSIBLE_VAULT;1.1;AES256
37623733663561366264613461376564656436656634393933343734356163383164363836663537
6238316161356163623733333734386462623337303835640a376165643661656463643730306135
31363334373237353136643937366134333935373764326561653338633432303864623337386335
6330316664373566610a643731383339356366613131633562333236623164326436626135613232
66386565366663623631393366316439643630623139343262663266396332616466323832616531
31353765363239316638383237373065643230363032326161373064633635633735643432393733
656463386638646230373237653632613438
