$ANSIBLE_VAULT;1.1;AES256
39643235313239663062373333636162333261376134333730656338303639663066386339333739
6462353531633133306563656466646635646362313135630a323635613661346439353135646434
35356337356261363230646637313334646336376630313164383266336265363866616330623736
6339393932663764310a626236613730626466303236303061623136376130343135623565346532
62343865613735376633343065373230646461653163616534663530643333363933626233376131
33306365363837663064373039633534653831313831383433336537346164353734623366366635
363335346664636630396336383364303863
